services:
  cm:
    build:
      context: ./docker/build/cm
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cm:${SITECORE_VERSION}
        TOOLS_IMAGE: ${TOOLS_IMAGE}
    volumes:
      - .\cm\website:C:\deploy
      - .\cm\log:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:/tools/entrypoints/iis/Development.ps1"
  cd:
    build:
      context: ./docker/build/cd
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cd:${SITECORE_VERSION}
        TOOLS_IMAGE: ${TOOLS_IMAGE}
    volumes:
      - .\cd\website:C:\deploy
      - .\cd\log:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:/tools/entrypoints/iis/Development.ps1"

