version: "2.4"

services:
  solution:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: .
      args:
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    scale: 0
  cm:
    build:
      context: ./docker/build/cm
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cm:${SITECORE_VERSION}
        TOOLS_IMAGE: ${TOOLS_IMAGE}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    volumes:
      - .\cm\website:C:\deploy
      - .\cm\log:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:/tools/entrypoints/iis/Development.ps1"
  cd:
    build:
      context: ./docker/build/cd
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cd:${SITECORE_VERSION}
        TOOLS_IMAGE: ${TOOLS_IMAGE}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    volumes:
      - .\cd\website:C:\deploy
      - .\cd\log:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:/tools/entrypoints/iis/Development.ps1"

